name: CI

on:
  workflow_dispatch:
    inputs:
      repository:
        name: 'DrakeHollow.Calculator'
  push:
    branches: [ main ]
env:
  appRoot: './Calculator'
  appRootWithoutPrefix: 'Calculator'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - run: cd ${{ env.appRoot }} && npm ci
    - run: cd ${{ env.appRoot }} && npm run build --if-present -- --prod --baseHref=${{ format('https://{0}.github.io/{1}/', github.repository_owner, github.event.repository.name) }}
#     - run: echo ${{ github.repository_owner }}
#     - run: echo ${{ github.event.repository.name }}
#       working-directory: ./
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ${{ format('{0}/dist', env.appRootWithoutPrefix) }}
        WORKSPACE: ${{ env.appRoot }}
        CLEAN: true 
